<?php 

class Notification extends CI_Model {

    function notify($to,$data)
    {
        $api_key="AAAAKvCx7Mw:APA91bHwCE5QlZuHVot3B6ga4nGe3tuRR1eGojNrJEQhXOceEBAmwaskFpnYQqQnWHktKHCeTmsBuWuSFBorJVzdTOlOmbBN1T0-_tGsCSe204rx_cACq-RAY6V8YMvgDvfcXmQaD8sX";
        $url="https://fcm.googleapis.com/fcm/send";

        $fields=json_encode(array(
            'to'=>$to,
            'notification'=>$data
        ));
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL,$url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

        $headers = array();
        $headers[] = 'Authorization:key='.$api_key;
        $headers[] = 'Content-Type:application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
    }
}